"""empty message

Revision ID: 1d6bb83f0b76
Revises: 
Create Date: 2020-05-26 21:42:43.685541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6bb83f0b76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tAddress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tAddress_id'), 'tAddress', ['id'], unique=True)
    op.create_table('tOpeningHoursTemplate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('mon', sa.String(length=255), nullable=True),
    sa.Column('tue', sa.String(length=255), nullable=True),
    sa.Column('wed', sa.String(length=255), nullable=True),
    sa.Column('thu', sa.String(length=255), nullable=True),
    sa.Column('fri', sa.String(length=255), nullable=True),
    sa.Column('sat', sa.String(length=255), nullable=True),
    sa.Column('sun', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tOpeningHoursTemplate_id'), 'tOpeningHoursTemplate', ['id'], unique=True)
    op.create_table('tRecurringSlotsTemplate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('slotLength', sa.Integer(), nullable=False),
    sa.Column('slotCapacity', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tRecurringSlotsTemplate_id'), 'tRecurringSlotsTemplate', ['id'], unique=True)
    op.create_table('tUser',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tUser_email'), 'tUser', ['email'], unique=True)
    op.create_index(op.f('ix_tUser_id'), 'tUser', ['id'], unique=True)
    op.create_index(op.f('ix_tUser_username'), 'tUser', ['username'], unique=True)
    op.create_table('tDistributionOwner',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('logoUrl', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('refAddressId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refAddressId'], ['tAddress.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_index(op.f('ix_tDistributionOwner_id'), 'tDistributionOwner', ['id'], unique=True)
    op.create_table('tDistributionPoint',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('logoUrl', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('maxCapacity', sa.Integer(), nullable=False),
    sa.Column('refAddressId', sa.String(length=36), nullable=False),
    sa.Column('refDistributionOwnerId', sa.String(length=36), nullable=False),
    sa.Column('refOpeningHoursTemplateId', sa.String(length=36), nullable=False),
    sa.Column('refRecurringSlotsTemplateId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refAddressId'], ['tAddress.id'], ),
    sa.ForeignKeyConstraint(['refDistributionOwnerId'], ['tDistributionOwner.id'], ),
    sa.ForeignKeyConstraint(['refOpeningHoursTemplateId'], ['tOpeningHoursTemplate.id'], ),
    sa.ForeignKeyConstraint(['refRecurringSlotsTemplateId'], ['tRecurringSlotsTemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tDistributionPoint_id'), 'tDistributionPoint', ['id'], unique=True)
    op.create_table('tBookableSlot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dateStart', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.Column('maxCapacity', sa.Integer(), nullable=False),
    sa.Column('currentCapacity', sa.Integer(), nullable=False),
    sa.Column('refDistributionPointId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refDistributionPointId'], ['tDistributionPoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tBookableSlot_id'), 'tBookableSlot', ['id'], unique=True)
    op.create_table('tCovidTracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numberOfPerson', sa.Integer(), nullable=False),
    sa.Column('refDistributionPointId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refDistributionPointId'], ['tDistributionPoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tCovidTracking_id'), 'tCovidTracking', ['id'], unique=True)
    op.create_table('tBookedSlot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numberOfPerson', sa.Integer(), nullable=False),
    sa.Column('confirmationCode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('refBookableSlotId', sa.String(length=36), nullable=False),
    sa.Column('refDistributionPointId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refBookableSlotId'], ['tBookableSlot.id'], ),
    sa.ForeignKeyConstraint(['refDistributionPointId'], ['tDistributionPoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tBookedSlot_id'), 'tBookedSlot', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tBookedSlot_id'), table_name='tBookedSlot')
    op.drop_table('tBookedSlot')
    op.drop_index(op.f('ix_tCovidTracking_id'), table_name='tCovidTracking')
    op.drop_table('tCovidTracking')
    op.drop_index(op.f('ix_tBookableSlot_id'), table_name='tBookableSlot')
    op.drop_table('tBookableSlot')
    op.drop_index(op.f('ix_tDistributionPoint_id'), table_name='tDistributionPoint')
    op.drop_table('tDistributionPoint')
    op.drop_index(op.f('ix_tDistributionOwner_id'), table_name='tDistributionOwner')
    op.drop_table('tDistributionOwner')
    op.drop_index(op.f('ix_tUser_username'), table_name='tUser')
    op.drop_index(op.f('ix_tUser_id'), table_name='tUser')
    op.drop_index(op.f('ix_tUser_email'), table_name='tUser')
    op.drop_table('tUser')
    op.drop_index(op.f('ix_tRecurringSlotsTemplate_id'), table_name='tRecurringSlotsTemplate')
    op.drop_table('tRecurringSlotsTemplate')
    op.drop_index(op.f('ix_tOpeningHoursTemplate_id'), table_name='tOpeningHoursTemplate')
    op.drop_table('tOpeningHoursTemplate')
    op.drop_index(op.f('ix_tAddress_id'), table_name='tAddress')
    op.drop_table('tAddress')
    # ### end Alembic commands ###
