"""empty message

Revision ID: e0d24e0c0ea9
Revises: 
Create Date: 2020-05-26 18:30:52.616842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0d24e0c0ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tCovidTracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numberOfPerson', sa.Integer(), nullable=False),
    sa.Column('refDistributionPointId', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['refDistributionPointId'], ['tDistributionPoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tCovidTracking_id'), 'tCovidTracking', ['id'], unique=True)
    op.drop_index('ix_tCompany_id', table_name='tCompany')
    op.drop_index('ix_tCompany_name', table_name='tCompany')
    op.drop_index('ix_tCompany_website', table_name='tCompany')
    op.drop_table('tCompany')
    op.drop_index('ix_brand_id', table_name='brand')
    op.drop_index('ix_brand_name', table_name='brand')
    op.drop_index('ix_brand_website', table_name='brand')
    op.drop_table('brand')
    op.drop_index('ix_default_db_content_id', table_name='default_db_content')
    op.drop_table('default_db_content')
    op.drop_index('ix_tOpeningHoursDetails_id', table_name='tOpeningHoursDetails')
    op.drop_table('tOpeningHoursDetails')
    op.add_column('tBookableSlot', sa.Column('refDistributionPointId', sa.String(length=36), nullable=False))
    op.drop_constraint('tBookableSlot_refDistributionPoint_fkey', 'tBookableSlot', type_='foreignkey')
    op.create_foreign_key(None, 'tBookableSlot', 'tDistributionPoint', ['refDistributionPointId'], ['id'])
    op.drop_column('tBookableSlot', 'refDistributionPoint')
    op.add_column('user', sa.Column('role', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.add_column('tBookableSlot', sa.Column('refDistributionPoint', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tBookableSlot', type_='foreignkey')
    op.create_foreign_key('tBookableSlot_refDistributionPoint_fkey', 'tBookableSlot', 'tDistributionPoint', ['refDistributionPoint'], ['id'])
    op.drop_column('tBookableSlot', 'refDistributionPointId')
    op.create_table('tOpeningHoursDetails',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('Mon', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Tue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Wed', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Thu', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Fri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Sat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Sun', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tOpeningHoursDetails_pkey')
    )
    op.create_index('ix_tOpeningHoursDetails_id', 'tOpeningHoursDetails', ['id'], unique=True)
    op.create_table('default_db_content',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='default_db_content_pkey')
    )
    op.create_index('ix_default_db_content_id', 'default_db_content', ['id'], unique=True)
    op.create_table('brand',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['tCompany.id'], name='brand_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='brand_pkey')
    )
    op.create_index('ix_brand_website', 'brand', ['website'], unique=True)
    op.create_index('ix_brand_name', 'brand', ['name'], unique=False)
    op.create_index('ix_brand_id', 'brand', ['id'], unique=True)
    op.create_table('tCompany',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tCompany_pkey')
    )
    op.create_index('ix_tCompany_website', 'tCompany', ['website'], unique=True)
    op.create_index('ix_tCompany_name', 'tCompany', ['name'], unique=False)
    op.create_index('ix_tCompany_id', 'tCompany', ['id'], unique=True)
    op.drop_index(op.f('ix_tCovidTracking_id'), table_name='tCovidTracking')
    op.drop_table('tCovidTracking')
    # ### end Alembic commands ###
